let
	sourceId = "sourceId",
	tableId = "tableId",

    body = "

		**{**
		 ** ""dimensions"": [**

			{
			  ""code"": ""string"",
			  ""filter"": ""string"",
			  ""values"": [
				""string""
			  ]
			}
		
		  ],

		  ""response"": {
			""format"": ""string"",
			""maxRowCount"": 0
		  }
		}

	"*
	
	
,
    Response= 
    Csv.Document(Web.Contents("https://statistikk-data.fhi.no/api/open/v1/" & sourceId & "/Table/" & tableId & "/data",
    [Content=Text.ToBinary(body), 
    Headers=[#"Content-Type"="application/json"]]),
    [Delimiter=";", 
    Encoding=65001, 
    QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Response, [PromoteAllScalars=true])
in
    #"Promoted Headers"
