let
	sourceId = "nokkel",
	tableId = "401",

    body = "

		{
		  ""dimensions"": [

			{
			  ""code"": ""AAR"",
			  ""filter"": ""top"",
			  ""values"": [
				""2""
			  ]
			}
		,

			{
				  ""code"": ""GEO"",
				  ""filter"": ""all"",
				  ""values"": [
					""32**""
				  ]
			},
				{
					""code"": ""TYPE_VALG"",
					""filter"": ""item"",
					""values"": [
						""KOMMUNEVALG"",
						""STORTINGSVALG""
					]
					},
			{
				  ""code"": ""MEASURE_TYPE"",
				  ""filter"": ""item"",
				  ""values"": [
					""RATE"",
					""SMR""
				  ]
			}
		  ],

		  ""response"": {
			""format"": ""csv2"",
			""maxRowCount"": 50000
		  }
		}

	"
	
	
,
    Response= 
    Csv.Document(Web.Contents("https://statistikk-data.fhi.no/api/open/v1/" & sourceId & "/Table/" & tableId & "/data",
    [Content=Text.ToBinary(body), 
    Headers=[#"Content-Type"="application/json"]]),
    [Delimiter=";", 
    Encoding=65001, 
    QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Response, [PromoteAllScalars=true])
in
    #"Promoted Headers"
